'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class ArqueoTransito1

    '''<summary>
    '''btnExportPdf control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnExportPdf As Global.DevExpress.Web.ASPxButton

    '''<summary>
    '''btnExportarXls control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnExportarXls As Global.DevExpress.Web.ASPxButton

    '''<summary>
    '''BootstrapFormLayout control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BootstrapFormLayout As Global.DevExpress.Web.Bootstrap.BootstrapFormLayout

    '''<summary>
    '''dtpFecha control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dtpFecha As Global.DevExpress.Web.Bootstrap.BootstrapDateEdit

    '''<summary>
    '''cmbBoveda control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbBoveda As Global.DevExpress.Web.Bootstrap.BootstrapComboBox

    '''<summary>
    '''btnBuscar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnBuscar As Global.DevExpress.Web.Bootstrap.BootstrapButton

    '''<summary>
    '''txtSaldoInicial control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSaldoInicial As Global.DevExpress.Web.Bootstrap.BootstrapTextBox

    '''<summary>
    '''txtAcreditaciones control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAcreditaciones As Global.DevExpress.Web.Bootstrap.BootstrapTextBox

    '''<summary>
    '''txtRecolecciones control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtRecolecciones As Global.DevExpress.Web.Bootstrap.BootstrapTextBox

    '''<summary>
    '''txtSaldoFinal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSaldoFinal As Global.DevExpress.Web.Bootstrap.BootstrapTextBox

    '''<summary>
    '''ASPxGridViewAcreditaciones control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxGridViewAcreditaciones As Global.DevExpress.Web.ASPxGridView

    '''<summary>
    '''ASPxGridViewRecolecciones control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxGridViewRecolecciones As Global.DevExpress.Web.ASPxGridView

    '''<summary>
    '''GridViewExport control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GridViewExport As Global.DevExpress.Web.ASPxGridView
End Class
